services:
  db:
    image: postgres:16
    container_name: budgetair-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  users:
    image: ghcr.io/johanan26/cicd2-budetair-user/budgetair_user:latest
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/users_db
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  flights:
    image: ghcr.io/sean-maloney/cicd2-budgetair-flight/budgetair_flight:latest
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/flights_db
    ports:
      - "8003:8003"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
   

  payments:
    image: ghcr.io/johanan26/cicd2-budget-air-payment/budgetair_payment:latest
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/payments_db
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  task:
    image: ghcr.io/johanan26/cicd2-budget-air-task/budgetair_task:latest
    environment:
      USERS_URL: http://users:8001
      FLIGHTS_URL: http://flights:8003
      PAYMENTS_URL: http://payments:8002
      REQUEST_TIMEOUT_SECONDS: "10"
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/task_db
    ports:
      - "8000:8000"
    depends_on:
      - users
      - flights
      - payments
    restart: unless-stopped

  frontend:
    image: ghcr.io/johanan26/cicd2-budget-air-frontend/budgetair_frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - task
    restart: unless-stopped

volumes:
  pgdata:
