services:
  budgetair_user:
    image: ghcr.io/johanan26/cicd2-budetair-user/budgetair_user
    networks:
      - labnet

  budgetair_flight:
    image: ghcr.io/sean-maloney/cicd2-budgetair-flight/budgetair_flight
    networks:
      - labnet

  budgetair_payment:
    image: ghcr.io/johanan26/cicd2-budget-air-payment/budgetair_payment
    networks:
      - labnet

  budgetair_task:
    image: ghcr.io/johanan26/cicd2-budget-air-task/budgetair_task
    env_file: ./.env
    depends_on:
      - budgetair_user
      - budgetair_flight
      - budgetair_payment
    networks:
      - labnet
networks:
  labnet:
